@Primes.WebApi_HostAddress = http://localhost:5103

### Check is a prime number - true
GET {{Primes.WebApi_HostAddress}}/PrimeNumber/17
Accept: application/json

### Check is a prime number - false
GET {{Primes.WebApi_HostAddress}}/PrimeNumber/800
Accept: application/json

### Get next prime number
GET {{Primes.WebApi_HostAddress}}/PrimeNumber/next-after/17
Accept: application/json
